

services:

  frontend:
    build: ./client
    ports:
      - "5173:5173"

    volumes:
      - ./client:/app
      - /app/node_modules

    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

